# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.CharField(default='http://nowhere.com', max_length=256),
            preserve_default=False,
        ),
    ]
